# built with Flutter 3.19.4 (Apple M1), Dart 3.3.2, CocoaPods 1.16.2
name: lasnotes
description: "Las Notes mobile"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: 2.3.3                   # SQLite DB support
  sqflite_common_ffi: 2.3.3        # necessary SQLite libs: https://stackoverflow.com/q/76158800
  markdown_widget: 2.3.2+8         # markdown widget
  file_picker: 8.0.5               # open-file dialog
  scoped_model: 2.0.0              # app state management
  path: 1.9.0                      # path manipulation (basename, etc.)
  flutter_platform_alert: 0.8.0    # native dialogs
  native_context_menu: 0.2.2+5     # native context menu (desktop only)
  window_manager: 0.4.3            # set window title in runtime (desktop only)
  shared_preferences: 2.2.2        # local key-value storage for settings
  package_info_plus: 8.0.2         # get version, build and app name
  share_plus: 7.2.2                # share-dialog for iOS share

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
